### ISSUE TITLE
[Вопрос или улучшение] Как это работает

### ISSUE THREAD

**Issue by mani1232** [SkyWatcher2019/LimboQueue#11]
server-offline: "<red>Server is offline." - есть такая строка
Но при этом если сервер выключен игрока почему то кикает велосити

**Comment by akbe2020** [comment]
server-offline это строчка из какого конфига?

**Comment by mani1232** [comment]
> server-offline это строчка из какого конфига?

```
main:
  # Serializers: LEGACY_AMPERSAND, LEGACY_SECTION, MINIMESSAGE
  serializer: "MINIMESSAGE"
  server: "survival"
  # Server checking interval in seconds
  check-interval: 2
  world:
    # Dimensions: OVERWORLD, NETHER, THE_END
    dimension: "THE_END"

messages:
  queue-message: "Your position in queue: {0}"
  server-offline: "<red>Server is offline."
  reload: "<green>LimboQueue reloaded!"
  reload-failed: "<red>Reload failed!"
```
